[tool.poetry]
name = "CubicalRipser_3dim"
version = "0.0.15"
description = "Cubical Ripser Python binding"
authors = ["shingo-murakami <murakami.shingo.098@s.kyushu-u.ac.jp>"]
license = "MIT"
repository = "https://github.com/shingo-murakami/CubicalRipser_3dim.git"

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["setuptools", "wheel", "cmake>=3.5.0", "pybind11"]
