name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
  
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python -
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel
  
    - name: Install pybind11
      run: pip install pybind11
      
  
    - name: Compile on Ubuntu
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH="C:/Users/shing/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages" -Dpybind11_DIR=/path/to/pybind11Config.cmake ..
        cmake --build .
      
  build_mac:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python -

    - name: Install dependencies
      run: |
        brew update  # macOS環境でのパッケージ更新
        python -m pip install --upgrade pip
      
    - name: Upgrade setuptools
      run: python -m pip install --upgrade setuptools
      
    - name: Install wheel
      run: python -m pip install wheel
    
    - name: Install pybind11
      run: |
        pip install pybind11
        pip install "pybind11[global]"
    
    - name: Compile on macOS
      run: |
        python setup.py sdist bdist_wheel

  build_windows:
    runs-on: windows-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Upgrade setuptools
      run: python -m pip install --upgrade setuptools

    - name: Install wheel
      run: python -m pip install wheel
      
    - name: Install pybind11
      run: |
        pip install pybind11
        pip install "pybind11[global]"

    - name: Compile on Windows
      run: |
        python setup.py sdist bdist_wheel

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel twine setuptools
  
    - name: Install pybind11
      run: |
        pip install pybind11
        pip install "pybind11[global]"
  
    - name: Build and upload
      run: |
        twine upload --repository-url https://test.pypi.org/legacy/ dist/* --verbose
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
