name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python -
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        

    - name: Compile on Ubuntu
      run: |
        # Compile commands for Ubuntu

  build_mac:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python -

    - name: Install dependencies
      run: |
        brew update  # macOS環境でのパッケージ更新
        python -m pip install --upgrade pip
      

    - name: Compile on macOS
      run: |
        # Compile commands for macOS

  build_windows:
    runs-on: windows-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Compile on Windows
      run: |
        # Compile commands for Windows
        

  test:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
  
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m poetry install
  
    - name: Run tests
      run: |
        # Test commands

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel twine setuptools
    
    - name: Install pybind11
      run: |
        pip install pybind11
        pip install "pybind11[global]"

    - name: Build distribution
      run: |
        python setup.py bdist_wheel

    - name: Build and upload
      run: |
        python setup.py sdist bdist_wheel
        twine upload --repository-url https://test.pypi.org/legacy/ dist/* --verbose
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
    